# This configuration compares LLM output of 2 prompts x 2 GPT models across 3 test cases.
# Learn more: https://promptfoo.dev/docs/configuration/guide
description: 'Submission Eval'

prompts:
  - prompts/prompt.txt
    

providers:
  - openai:gpt-3.5-turbo

tests:
  - ./tests/python.yaml
  - ./tests/java.yaml


